### PR TITLE
Support headers

### PR DESCRIPTION
**Pull request by Lonelind**
Hi!

This PR adds support for headers, partly resolving #57.

Test cases with arrays also added.

### CODE REVIEW

**Comment by raveclassic** [comment]
Hi @Lonelind, thank you for the PR!

Could you please clarify what you mean by "partially resolving #57"?

**Comment by raveclassic** [comment]
@Lonelind Please open a satellite issue tracking swagger2.0 spec if you are not going to support it in this PR (I wouldn't suggest to do it).

**Comment by Lonelind** [comment]
I didn't add formData there but I guess it'd be about the same. Currently, this only helps with headers because it's really needed on my project due to the API design.

**Comment by raveclassic** [comment]
@Lonelind Please open issues to track missing things :)

**Comment by Lonelind** [comment]
Swagger 2.0 is supported

**Comment by raveclassic** [comment]
@Lonelind Sorry, didn't notice that! Thanks, LGTM. But please open an issue for the missing parts (FormData etc.)

**Review by raveclassic — APPROVED** [review]

**Comment by Lonelind** [comment]
I'd rather add a notice to #57 that headers are done and resolve #39 because this PR just adds one thing of many from the list.

**Pull request merged**
