### PR TITLE
Add non empty array support to async-api

### PR DESCRIPTION
**Pull request by coolassassin**
Async-api support, same as in this MR:
https://github.com/devexperts/swagger-codegen-ts/pull/146/files

### CODE REVIEW

**Comment by kokovtsev** [comment]
Thanks @coolassassin for taking the time to improve this! We'll review shortly and make a release

**Review by kokovtsev — APPROVED** [review]

**Comment by coolassassin** [comment]
Up. Looks like the one of jobs is broken @kokovtsev

**Comment by scink** [comment]
Screenshot 2022-01-27 at 14 45 08
@kokovtsev please check CLA

**Comment by kokovtsev** [comment]
@coolassassin the CLA app should be up now, could you please check and sign it?

**Pull request merged**
