### PR TITLE
OpenApi string field with format date has bad path in generated typescript

### PR DESCRIPTION
**Pull request by VKamotin**

### CODE REVIEW

**Comment by kokovtsev** [comment]
@raveclassic @sutarmin anything we can do to help to get this merged?

**Comment by sutarmin** [comment]
Very sorry, but I don't have enough time right now for a proper review, tbh, since I'm not really familiar with this codebase and there is a lot of things for me to comprehend. @raveclassic do you think you can spend some time on review this week?

**Comment by raveclassic** [comment]
Hi @VKamotin , thanks for the PR. However this is not how the things are supposed to work. We should not work with paths by hand but use refs instead. Please take a look at how `openapi3.utils` file is passed around the files.

**Review by raveclassic — CHANGES_REQUESTED** [review]
see prev comment

**Comment by raveclassic** [comment]
@VKamotin take a look at https://github.com/devexperts/swagger-codegen-ts/pull/131

**Comment by VKamotin** [comment]
Wow, thank you!

**Pull request closed without merging**
